# Generated by Django 2.2.5 on 2019-09-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sale'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
