# Generated by Django 2.2.5 on 2019-09-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['discount_price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
