# Generated by Django 2.2.5 on 2019-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191101_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_seo',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
