# Generated by Django 2.2.5 on 2019-09-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
