# Generated by Django 2.2.5 on 2019-09-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190925_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка в процентах'),
        ),
    ]
