# Generated by Django 2.2.5 on 2019-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191127_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_seo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title'),
        ),
    ]
