# Generated by Django 2.2.5 on 2019-09-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190925_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['discount_price', 'price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
