# Generated by Django 2.2.5 on 2019-09-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190925_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'discount_price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
