# Generated by Django 2.2.5 on 2019-09-26 11:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190926_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_seo',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
