# Generated by Django 2.2.5 on 2019-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20190926_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_seo',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
