# Generated by Django 2.2.5 on 2019-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190926_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_seo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_seo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
