# Generated by Django 2.2.5 on 2019-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190926_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_seo',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_seo',
            field=models.CharField(blank=True, max_length=140, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
