# Generated by Django 2.2.5 on 2019-09-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_updated_at'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
