# Generated by Django 2.2.5 on 2019-09-24 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now, max_length=300, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
