# Generated by Django 2.2.5 on 2019-09-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
