# Generated by Django 2.2.5 on 2019-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_choice',
            field=models.BooleanField(blank=True, choices=[('С', 'Самовывоз'), ('Д', 'Доставка')], default=True, verbose_name='Способ доставки'),
        ),
    ]
