# Generated by Django 2.2.5 on 2019-10-09 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_delivery_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_choice',
            field=models.CharField(choices=[('С', 'Самовывоз'), ('Д', 'Доставка')], default=django.utils.timezone.now, max_length=2, verbose_name='Способ доставки'),
            preserve_default=False,
        ),
    ]
