# Generated by Django 2.2.5 on 2019-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20191009_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_choice',
            field=models.CharField(choices=[('С', 'Самовывоз'), ('Д', 'Доставка')], default='С', max_length=20, verbose_name='Способ доставки'),
        ),
    ]
