# Generated by Django 2.2.5 on 2019-10-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20191009_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_choice',
        ),
    ]
